name: Deploy Dev
on:
  push:
    branches: ["dev"]

env:
  AWS_REGION: us-east-1
  PROJECT_NAME: icrop-weather
  ENVIRONMENT: dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN_DEV }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Terraform infra (dev)
        working-directory: infra/terraform
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          TF_VAR_region: ${{ env.AWS_REGION }}
        run: |
          terraform init -input=false
          terraform workspace select dev || terraform workspace new dev
          terraform apply -auto-approve -var-file=environments/dev/terraform.tfvars
          echo "ECR_REPO=$(terraform output -raw ecr_repo)" >> $GITHUB_ENV
          echo "ALB_URL=$(terraform output -raw alb_url)" >> $GITHUB_ENV

      - name: Build and push image
        run: |
          COMMIT=${GITHUB_SHA::7}
          IMAGE=${ECR_REPO}:${COMMIT}
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE_URI=$IMAGE" >> $GITHUB_ENV

      - name: Update service with new image
        working-directory: infra/terraform
        env:
          TF_VAR_project_name: ${{ env.PROJECT_NAME }}
          TF_VAR_environment: ${{ env.ENVIRONMENT }}
          TF_VAR_region: ${{ env.AWS_REGION }}
          TF_VAR_image: ${{ env.IMAGE_URI }}
        run: |
          terraform apply -auto-approve -var-file=environments/dev/terraform.tfvars -var="image=${TF_VAR_image}"

      - name: Output URL
        run: echo "DEV URL: $ALB_URL"